name: Manual Post to Social

on:
  workflow_dispatch: {}  # no inputs

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger scheduled-post (auto-pick next JSON in queue)
        env:
          SCHEDULED_POST_URL: ${{ secrets.SCHEDULED_POST_URL }}
        run: |
          # Optional payload: {"max_scan": 5} limits how many objects the function scans
          curl -sS -X POST "$SCHEDULED_POST_URL" \
            -H "Content-Type: application/json" \
            -d '{"max_scan":5}' \
            -w "\nHTTP %{http_code}\n"
